BaSD-2021/David-MindSet-server

index.js, package-lock.json, package.json
=> Ft setup DotEnv

controllers/companies.js, public/index.html, routes/index.js
=> new folder structure

.eslintrc.js, controllers/administrators.js, controllers/applications.js, controllers/candidates.js, controllers/companies.js, controllers/interviews.js, controllers/open-positions.js, controllers/profile-types.js, controllers/psychologists.js, controllers/sessions.js, index.js, models/Sessions.js, package-lock.json, validators/sessions.js
Responses format:
data: array in getAll, an element in the others.
=> [FIX] - MS-24: Refactor backend responses

controllers/applications.js, models/Applications.js
=> MS-25: refactor applications model

controllers/candidates.js, models/Candidates.js, public/js/candidates/formCandidates.js, public/js/candidates/listCandidates.js
Change graduationYear number type to Date type
Add "type" property in education.
=> MS: change candidates model - education

controllers/auth.js, helpers/firebase/index.js, middleware/authMiddleware.js, models/Administrators.js, models/Candidates.js, models/Psychologists.js, models/Sessions.js, models/Users.js, package-lock.json, package.json, routes/administrators.js, routes/applications.js, routes/auth.js, routes/candidates.js, routes/companies.js, routes/index.js, routes/interviews.js, routes/open-position.js, routes/profile-types.js, routes/psychologists.js, routes/sessions.js, validators/auth.js
=> [FEATURE] - MS-54: Firebase implementation

controllers/auth.js, models/Users.js
=> [FIX] MS-80: fix roles in login, remove roles from user model

models/Candidates.js, routes/candidates.js, validators/candidates.js
Add time range property in candidates model, create time range validations and add it into put route
=> [FEATURE] MS-44: Candidates Time Range

models/Candidates.js, public/js/candidates/formCandidates.js
Change type in course's year, `type: date` instead number..
=> MS-42: minor change on courses date

.eslintrc.js, .prettierrc.json, controllers/candidate/sessions.js, controllers/psychologists.js, controllers/sessions.js, helpers/index.js, models/Psychologists.js, models/Sessions.js, routes/candidate/index.js, routes/candidate/sessions.js, routes/index.js, validators/psychologists.js, validators/sessions.js
- Modified Psychologists and Sessions models
- Add logic to get all available times
- Add logic to create a session
- Add validation to check if a session has already been taken
=> [FEATURE] - MS-66: Candidate - Sessions Sign-up

controllers/candidate/sessions.js, controllers/candidates.js, models/Candidates.js, routes/candidate/sessions.js
- Modify Candidate model
- Add logic to get, edit and delete scheduled sessions
=> [FEATURE] - MS-66: Candidate - Session Profile

models/Candidates.js
add a `type: hobbies` inside the array of Hobbies
=> [FEATURE] MS-43: Minor change on Hobbies

controllers/admin/applications.js, controllers/admin/open-positions.js, models/Applications.js, models/OpenPosition.js, routes/admin/applications.js
- Modify Positions model and controller
- Create endpoint to get number of applications for each profile
- Modify Applications model
- Get applications filtered by date and profile
=> [FEATURE] - MS-74: Admin - Reports

controllers/admin/administrators.js, controllers/admin/candidates.js, controllers/admin/psychologists.js, controllers/auth.js, helpers/index.js, models/Candidates.js, routes/admin/administrators.js, routes/admin/candidates.js, routes/admin/psychologists.js, routes/index.js
Refactor admin-psychologist feature.
Refactor admin-candidate feature.
Multiple fixes in many files.
=> [FEATURE] MS-76: Admin Psychologist - Candidate

controllers/psychologist/psychologists.js, routes/psychologist/psychologists.js, validators/psychologists.js
Remove useless endpoints.
Add timeRange validations
=> [FEATURE] MS-69: refactor psychologist feature

controllers/admin/interviews.js, controllers/candidate/interviews.js, models/Interviews.js, routes/candidate/interviews.js
- Modify Interviews model and controller (change status, add result)
- Adapt endpoint to get all pending interviews
- Create endpoint to get all scheduled interviews
- Create endpoint to get all completed interviews
- Endpoint and logic to accept/decline/reschedule an interview
=> [FEATURE] - MS-63-64: Candidate - Interviews

controllers/admin/sessions.js, controllers/candidate/sessions.js, models/Candidates.js, models/Sessions.js, routes/candidate/sessions.js, validators/sessions.js
=> [FIX] - MS-86: Change sessions validations

middleware/authMiddleware.js, routes/admin/administrators.js, routes/admin/applications.js, routes/admin/candidates.js, routes/admin/companies.js, routes/admin/interviews.js, routes/admin/open-position.js, routes/admin/profile-types.js, routes/admin/psychologists.js, routes/admin/sessions.js, routes/auth.js, routes/candidate/profile.js, routes/candidate/sessions.js, routes/index.js, routes/open-position.js, routes/psychologist/candidates.js, routes/psychologist/profile-types.js, routes/psychologist/psychologists.js, routes/psychologist/sessions.js
=> [FIX] - MS-82: Add role middlewares

controllers/admin/interviews.js, controllers/admin/sessions.js, routes/admin/interviews.js, routes/admin/sessions.js
Add logic to delete outdated sessions and interviews when deleting a candidate or psychologist.
=> [FIX] - MS-85: Delete outdated Sessions / Interviews

validators/interviews.js, validators/sessions.js
=> [FIX] - MS: Fix sessions and interviews timezone bug
